[customizations.installer.kickstart]
contents = """
graphical

# Localization
keyboard --vckeymap=us-acentos --xlayouts='us','us (altgr-intl)'
lang en_US.UTF-8
timezone Europe/Paris --utc

# Root password
rootpw --iscrypted lock
"""

[[customizations.user]]
name = "arouene"
password = "ch@ngem3"
groups = ["wheel"]
